const mockReview = [
  {
    id: '1',
    image: '/images/Image_default_profile_image.png',
    name: 'test1',
    date: '2070.06.13',
    text: '패러글라이딩 정말 최고였어요! 하늘을 나는 기분이 너무 짜릿했어요.',
  },
  {
    id: '2',
    image: '/images/Image_default_profile_image.png',
    name: 'test2',
    date: '2070.06.13',
    text: '서핑 수업 덕분에 새로운 취미를 찾았어요. 강사님도 친절하고 재미있었어요.',
  },
  {
    id: '3',
    image: '/images/Image_default_profile_image.png',
    name: 'test3',
    date: '2070.06.13',
    text: '하이킹 코스가 너무 아름다웠습니다. 자연과 함께하는 시간이 정말 힐링이었어요.',
  },
  {
    id: '4',
    image: '/images/Image_default_profile_image.png',
    name: 'test4',
    date: '2070.06.13',
    text: '스쿠버 다이빙 처음 해봤는데, 바닷속 세상이 이렇게 멋진 줄 몰랐어요. 또 하고 싶어요!',
  },
  {
    id: '5',
    image: '/images/Image_default_profile_image.png',
    name: 'test5',
    date: '2070.06.13',
    text: '집라인 타면서 느낀 스릴은 잊을 수 없을 거예요. 다시 도전하고 싶습니다!',
  },
  {
    id: '6',
    image: '/images/Image_default_profile_image.png',
    name: 'test6',
    date: '2070.06.13',
    text: '래프팅 정말 재미있었어요! 친구들과 함께해서 더 즐거웠습니다.',
  },
  {
    id: '7',
    image: '/images/Image_default_profile_image.png',
    name: 'test7',
    date: '2070.06.13',
    text: '승마 체험 덕분에 말을 가까이에서 접할 수 있어 좋았어요. 좋은 추억이 생겼어요.',
  },
  {
    id: '8',
    image: '/images/Image_default_profile_image.png',
    name: 'test8',
    date: '2070.06.13',
    text: '카약킹으로 강을 따라 내려가는 경험이 정말 색다르고 즐거웠어요. 꼭 다시 가고 싶어요.',
  },
  {
    id: '9',
    image: '/images/Image_default_profile_image.png',
    name: 'test9',
    date: '2070.06.13',
    text: '암벽 등반은 체력 소모가 컸지만 성취감이 정말 컸어요. 도전해볼 가치가 있었어요.',
  },
  {
    id: '10',
    image: '/images/Image_default_profile_image.png',
    name: 'test10',
    date: '2070.06.13',
    text: '낚시 체험이 생각보다 재미있었어요. 잡은 물고기로 요리도 해 먹었답니다!',
  },
  {
    id: '11',
    image: '/images/Image_default_profile_image.png',
    name: 'test11',
    date: '2070.06.13',
    text: '스노클링으로 다양한 물고기를 볼 수 있었어요. 바닷속 풍경이 정말 아름다웠습니다.',
  },
  {
    id: '12',
    image: '/images/Image_default_profile_image.png',
    name: 'test12',
    date: '2070.06.13',
    text: 'ATV 타면서 느낀 속도감이 최고였어요. 자연 속에서 즐길 수 있어 더 좋았어요.',
  },
  {
    id: '13',
    image: '/images/Image_default_profile_image.png',
    name: 'test13',
    date: '2070.06.13',
    text: '요트 체험이 너무 멋졌어요. 바다 위에서 즐긴 시간은 잊지 못할 거예요.',
  },
  {
    id: '14',
    image: '/images/Image_default_profile_image.png',
    name: 'test14',
    date: '2070.06.13',
    text: '스카이다이빙은 정말 최고의 경험이었어요. 자유롭게 하늘을 나는 기분, 잊을 수 없어요!',
  },
  {
    id: '15',
    image: '/images/Image_default_profile_image.png',
    name: 'test15',
    date: '2070.06.13',
    text: '눈썰매 체험이 정말 즐거웠어요. 가족과 함께여서 더 행복했어요.',
  },
  {
    id: '16',
    image: '/images/Image_default_profile_image.png',
    name: 'test16',
    date: '2070.06.13',
    text: '패들 보트 타면서 여유롭게 물 위를 떠다니는 시간이 좋았어요. 강력 추천합니다!',
  },
  {
    id: '17',
    image: '/images/Image_default_profile_image.png',
    name: 'test17',
    date: '2070.06.13',
    text: '트레킹 코스가 너무 잘 되어 있어서 힘들지 않게 즐길 수 있었어요. 자연이 아름다웠어요.',
  },
  {
    id: '18',
    image: '/images/Image_default_profile_image.png',
    name: 'test18',
    date: '2070.06.13',
    text: '클레이 사격 체험이 생각보다 재미있었어요. 집중력도 키울 수 있어 좋았어요.',
  },
  {
    id: '19',
    image: '/images/Image_default_profile_image.png',
    name: 'test19',
    date: '2070.06.13',
    text: '번지 점프는 정말 짜릿했어요! 무서웠지만 도전하길 잘한 것 같아요.',
  },
  {
    id: '20',
    image: '/images/Image_default_profile_image.png',
    name: 'test20',
    date: '2070.06.13',
    text: '스키를 처음 배웠는데 너무 재미있었어요. 겨울이 오기만을 기다리고 있어요!',
  },
];

export default mockReview;
